// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let decodeString = Stdlib_JSON.Decode.string;

function decodePatch(json, decodeValue) {
  let obj = Stdlib_JSON.Decode.object(json);
  if (obj === undefined) {
    return;
  }
  let match = Stdlib_Option.flatMap(obj["key"], decodeString);
  let match$1 = Stdlib_Option.flatMap(obj["value"], decodeValue);
  if (match !== undefined && match$1 !== undefined) {
    return {
      key: match,
      value: Primitive_option.valFromOption(match$1)
    };
  }
}

function start(url, decodeValue, onPatch, onError) {
  let source = new EventSource(url);
  source.addEventListener("change", evt => {
    let json;
    try {
      json = JSON.parse(evt.data);
    } catch (exn) {
      return Stdlib_Option.forEach(onError, cb => cb("Failed to parse patch json"));
    }
    let patch = decodePatch(json, decodeValue);
    if (patch !== undefined) {
      return onPatch(patch);
    } else {
      return Stdlib_Option.forEach(onError, cb => cb("Unexpected patch format"));
    }
  });
  return {
    source: source,
    _phantom: undefined
  };
}

function stop(client) {
  client.source.close();
}

let StringMap;

export {
  StringMap,
  decodeString,
  decodePatch,
  start,
  stop,
}
/* No side effect */
