// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";

function make(start, stop, getState) {
  let subscribers = {
    contents: []
  };
  let nextId = {
    contents: 0
  };
  let publish = () => {
    let state = getState();
    console.log("notify", state);
    Belt_Array.forEach(subscribers.contents, sub => sub.run(state));
  };
  let subscribe = run => {
    let id = nextId.contents;
    nextId.contents = id + 1 | 0;
    subscribers.contents = Belt_Array.concatMany([
      [{
          id: id,
          run: run
        }],
      subscribers.contents
    ]);
    if (subscribers.contents.length === 1) {
      start();
    }
    run(getState());
    return () => {
      subscribers.contents = Belt_Array.keep(subscribers.contents, sub => sub.id !== id);
      if (subscribers.contents.length === 0) {
        return stop();
      }
    };
  };
  return {
    subscribe: subscribe,
    publish: publish
  };
}

export {
  make,
}
/* No side effect */
