// Generated by ReScript, PLEASE EDIT WITH CARE

import * as FeedClient from "./FeedClient.res.mjs";
import * as ReadableStore from "./ReadableStore.res.mjs";

function make(url, decodeValue) {
  let state = {
    contents: {}
  };
  let connection = {
    contents: undefined
  };
  let publishRef = {
    contents: () => {}
  };
  let onError = prim => {
    console.error(prim);
  };
  let onPatch = patches => {
    console.log("onPatch.patches", patches);
    patches.forEach(patch => {
      state.contents[patch.key] = patch.value;
    });
    console.log("onPatch.state", state.contents);
    publishRef.contents();
  };
  let start = () => {
    let conn = FeedClient.start(url, decodeValue, onPatch, onError);
    let match = connection.contents;
    if (match !== undefined) {
      return;
    } else {
      connection.contents = conn;
      return;
    }
  };
  let stop = () => {
    let client = connection.contents;
    if (client !== undefined) {
      FeedClient.stop(client);
      connection.contents = undefined;
      return;
    }
  };
  let getState = () => state.contents;
  let store = ReadableStore.make(start, stop, getState);
  publishRef.contents = store.publish;
  return {
    subscribe: store.subscribe
  };
}

export {
  make,
}
/* No side effect */
