// Generated by ReScript, PLEASE EDIT WITH CARE

import * as FeedClient from "./FeedClient.res.mjs";
import * as ReadableStore from "./ReadableStore.res.mjs";
import * as Belt_MapString from "@rescript/runtime/lib/es6/Belt_MapString.js";

function make(url, decodeValue) {
  let state = {
    contents: undefined
  };
  let connection = {
    contents: undefined
  };
  let publishRef = {
    contents: () => {}
  };
  let onError = prim => {
    console.error(prim);
  };
  let onPatch = patch => {
    state.contents = Belt_MapString.set(state.contents, patch.key, patch);
    publishRef.contents();
  };
  let start = () => {
    let match = connection.contents;
    if (match !== undefined) {
      return;
    } else {
      connection.contents = FeedClient.start(url, decodeValue, onPatch, onError);
      return;
    }
  };
  let stop = () => {
    let client = connection.contents;
    if (client !== undefined) {
      FeedClient.stop(client);
      connection.contents = undefined;
      return;
    }
  };
  let getState = () => state.contents;
  let store = ReadableStore.make(start, stop, getState);
  publishRef.contents = store.publish;
  return {
    subscribe: store.subscribe
  };
}

let $$Map;

export {
  $$Map,
  make,
}
/* No side effect */
