// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as FeedClient from "./FeedClient.res.mjs";
import * as Belt_MapString from "@rescript/runtime/lib/es6/Belt_MapString.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

function make(url, decodeValue) {
  let state = {
    contents: undefined
  };
  let notifyRef = {
    contents: _state => {}
  };
  let connection = {
    contents: undefined
  };
  let onPatch = patch => {
    state.contents = Belt_MapString.set(state.contents, patch.key, patch);
    notifyRef.contents(state.contents);
  };
  let start = () => {
    let match = connection.contents;
    if (match !== undefined) {
      return;
    } else {
      connection.contents = FeedClient.start(url, decodeValue, onPatch, prim => {
        console.error(prim);
      });
      return;
    }
  };
  let stop = () => {
    let client = connection.contents;
    if (client !== undefined) {
      FeedClient.stop(client);
      connection.contents = undefined;
      return;
    }
  };
  let subscribers = {
    contents: []
  };
  let subscribe = run => {
    subscribers.contents = Belt_Array.concatMany([
      [run],
      subscribers.contents
    ]);
    notifyRef.contents = state => Belt_Array.forEach(subscribers.contents, cb => cb(state));
    if (subscribers.contents.length === 1) {
      start();
    }
    run(state.contents);
    return () => {
      subscribers.contents = Belt_Array.keep(subscribers.contents, cb => Primitive_object.notequal(cb, run));
      if (subscribers.contents.length === 0) {
        return stop();
      }
    };
  };
  return {
    subscribe: subscribe
  };
}

let $$Map;

export {
  $$Map,
  make,
}
/* No side effect */
