// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let decodeString = Stdlib_JSON.Decode.string;

function decodePatch(json, valueDecoder) {
  let obj = Stdlib_JSON.Decode.object(json);
  if (obj === undefined) {
    return;
  }
  let match = Stdlib_Option.flatMap(obj["key"], decodeString);
  let match$1 = Stdlib_Option.flatMap(obj["value"], valueDecoder);
  if (match !== undefined && match$1 !== undefined) {
    return {
      key: match,
      value: Primitive_option.valFromOption(match$1)
    };
  }
}

let StringMap;

export {
  StringMap,
  decodeString,
  decodePatch,
}
/* No side effect */
