// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function notify(subs, value) {
  Belt_Array.forEach(subs.contents, entry => entry.run(value));
}

function parsePatch(string) {
  try {
    let obj = Stdlib_JSON.Decode.object(JSON.parse(string));
    if (obj === undefined) {
      return;
    }
    let match = obj["key"];
    let match$1 = obj["value"];
    if (match === undefined) {
      return;
    }
    if (match$1 === undefined) {
      return;
    }
    let key = Stdlib_JSON.Decode.string(match);
    if (key !== undefined) {
      return {
        key: key,
        value: match$1
      };
    } else {
      return;
    }
  } catch (exn) {
    return;
  }
}

function make(url) {
  let state = {};
  let subscribers = {
    contents: []
  };
  let nextId = {
    contents: 0
  };
  let connection = {
    contents: undefined
  };
  let start = () => {
    let match = connection.contents;
    if (match !== undefined) {
      return;
    }
    let es = new EventSource(url);
    es.addEventListener("message", evt => {
      let match = parsePatch(evt.data);
      if (match !== undefined) {
        state[match.key] = match.value;
        return notify(subscribers, state);
      }
    });
    connection.contents = Primitive_option.some(es);
  };
  let stop = () => {
    let es = connection.contents;
    if (es !== undefined) {
      Primitive_option.valFromOption(es).close();
      connection.contents = undefined;
      return;
    }
  };
  let subscribe = run => {
    let id = nextId.contents;
    nextId.contents = id + 1 | 0;
    subscribers.contents = Belt_Array.concatMany([
      [{
          id: id,
          run: run
        }],
      subscribers.contents
    ]);
    if (subscribers.contents.length === 1) {
      start();
    }
    run(state);
    return () => {
      subscribers.contents = Belt_Array.keep(subscribers.contents, entry => entry.id !== id);
      if (subscribers.contents.length === 0) {
        return stop();
      }
    };
  };
  return {
    subscribe: subscribe
  };
}

export {
  notify,
  parsePatch,
  make,
}
/* No side effect */
