// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";

function make(initial) {
  let value = {
    contents: initial
  };
  let subscribers = {
    contents: []
  };
  let notify = () => Belt_Array.forEach(subscribers.contents, s => s(value.contents));
  let subscribe = run => {
    subscribers.contents = Belt_Array.concat(subscribers.contents, [run]);
    run(value.contents);
    return () => {
      subscribers.contents = Belt_Array.keep(subscribers.contents, s => s !== run);
    };
  };
  let set = v => {
    value.contents = v;
    notify();
  };
  let update = fn => {
    value.contents = fn(value.contents);
    notify();
  };
  return {
    subscribe: subscribe,
    update: update,
    set: set
  };
}

export {
  make,
}
/* No side effect */
