// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Common from "./Common.res.mjs";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

async function request(url) {
  let defaultErr = "Error processing API request";
  try {
    let resp = await fetch(url);
    let json = await resp.json();
    if (resp.ok) {
      return {
        TAG: "Ok",
        _0: json
      };
    } else {
      return {
        TAG: "Error",
        _0: Common.Err.parse(json, defaultErr)
      };
    }
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    if (exn.RE_EXN_ID === "JsExn") {
      return {
        TAG: "Error",
        _0: Common.Err.$$catch(exn._1, defaultErr)
      };
    }
    throw exn;
  }
}

let Get = {
  request: request
};

export {
  Get,
}
/* Common Not a pure module */
