// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Common from "./Common.res.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

async function request(url) {
  let defaultErr = "Error processing API get-request";
  try {
    let resp = await fetch(url);
    let json = await resp.json();
    if (resp.ok) {
      return {
        TAG: "Ok",
        _0: json
      };
    } else {
      return {
        TAG: "Error",
        _0: Common.Err.parse(json, defaultErr)
      };
    }
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    if (exn.RE_EXN_ID === "JsExn") {
      return {
        TAG: "Error",
        _0: Common.Err.$$catch(exn._1, defaultErr)
      };
    }
    throw exn;
  }
}

let Get = {
  request: request
};

async function request$1(url, key, value) {
  let defaultErr = "Error processing API patch-request";
  let body = `{"` + key + `":"` + value + `"}`;
  let headersDict = {
    "Content-Type": "application/json"
  };
  let init = {
    method: "PATCH",
    headers: Primitive_option.some(headersDict),
    body: Primitive_option.some(body)
  };
  try {
    let resp = await fetch(url, init);
    let json = await resp.json();
    if (resp.ok) {
      return {
        TAG: "Ok",
        _0: json
      };
    } else {
      return {
        TAG: "Error",
        _0: Common.Err.parse(json, defaultErr)
      };
    }
  } catch (raw_exn) {
    let exn = Primitive_exceptions.internalToException(raw_exn);
    if (exn.RE_EXN_ID === "JsExn") {
      return {
        TAG: "Error",
        _0: Common.Err.$$catch(exn._1, defaultErr)
      };
    }
    throw exn;
  }
}

let Patch = {
  request: request$1
};

export {
  Get,
  Patch,
}
/* Common Not a pure module */
