// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function make(msg) {
  return {
    msg: msg
  };
}

function buildDefault(defaultErr) {
  return Stdlib_Option.getOr(defaultErr, "Unexpexted");
}

function $$catch(exn, defaultErr) {
  let msg = Stdlib_JsExn.message(exn);
  if (msg !== undefined) {
    return {
      msg: msg
    };
  } else {
    return {
      msg: Stdlib_Option.getOr(defaultErr, "Unexpexted")
    };
  }
}

function parse(json, defaultErr) {
  return {
    msg: Stdlib_Option.getOr(Stdlib_Option.flatMap(Stdlib_Option.flatMap(Stdlib_JSON.Decode.object(json), obj => obj["msg"]), Stdlib_JSON.Decode.string), Stdlib_Option.getOr(defaultErr, "Unexpexted"))
  };
}

let Err = {
  make: make,
  buildDefault: buildDefault,
  $$catch: $$catch,
  parse: parse
};

export {
  Err,
}
/* Stdlib_JsExn Not a pure module */
