// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let decodeKey = Stdlib_JSON.Decode.string;

function decodePatch(json, decodeValue) {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return;
  }
  let match = Stdlib_Option.flatMap(json["key"], decodeKey);
  let match$1 = Stdlib_Option.flatMap(json["value"], decodeValue);
  if (match !== undefined && match$1 !== undefined) {
    return {
      key: match,
      value: Primitive_option.valFromOption(match$1)
    };
  }
}

function parsePatches(event, decodeValue, onError) {
  let json;
  try {
    json = JSON.parse(event.data);
  } catch (exn) {
    onError("Failed to parse json");
    return;
  }
  if (Array.isArray(json)) {
    return Stdlib_Array.filterMap(json, p => decodePatch(p, decodeValue));
  }
  if (json === null) {
    return;
  }
  switch (typeof json) {
    case "object" :
      return Stdlib_Option.map(decodePatch(json, decodeValue), p => [p]);
    default:
      return;
  }
}

function start(url, decodeValue, onPatch, onError) {
  let source = new EventSource(url);
  source.addEventListener("change", event => {
    let patches = parsePatches(event, decodeValue, onError);
    if (patches !== undefined) {
      return onPatch(patches);
    } else {
      return onError("Unexpected patch format");
    }
  });
  source.addEventListener("init", event => {
    let patches = parsePatches(event, decodeValue, onError);
    if (patches !== undefined) {
      return onPatch(patches);
    } else {
      return onError("Unexpected patch format");
    }
  });
  return {
    source: source,
    _phantom: undefined
  };
}

function stop(client) {
  client.source.close();
}

export {
  decodeKey,
  decodePatch,
  parsePatches,
  start,
  stop,
}
/* No side effect */
