// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Api from "./Api.res.mjs";
import * as Common from "./Common.res.mjs";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Store from "svelte/store";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

let getFieldUrl = "http://localhost:4000/store/fields";

let feedSourceUrl = "http://localhost:4000/store/feed";

function parseField(json) {
  return Stdlib_Option.flatMap(Stdlib_JSON.Decode.object(json), obj => {
    let options = [
      "key",
      "name",
      "unit"
    ].map(k => Stdlib_Option.flatMap(obj[k], Stdlib_JSON.Decode.string));
    if (options.length !== 3) {
      return;
    }
    let key = options[0];
    if (key === undefined) {
      return;
    }
    let name = options[1];
    if (name === undefined) {
      return;
    }
    let u = options[2];
    return {
      key: key,
      name: name,
      unit: u
    };
  });
}

function parseFields(json) {
  return Stdlib_Option.flatMap(Stdlib_JSON.Decode.array(json), arr => Stdlib_Option.all(arr.map(parseField)));
}

async function fetch() {
  let err = await Api.Get.request(getFieldUrl);
  if (err.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: err._0
    };
  }
  let fields = parseFields(err._0);
  if (fields !== undefined) {
    return {
      TAG: "Ok",
      _0: fields
    };
  } else {
    return {
      TAG: "Error",
      _0: Common.Err.make("Failed to parse fields", undefined)
    };
  }
}

let Fields = {
  parseField: parseField,
  parseFields: parseFields,
  fetch: fetch
};

function parsePatch(json) {
  return Stdlib_Option.flatMap(Stdlib_JSON.Decode.object(json), obj => {
    let options = [
      "key",
      "value"
    ].map(k => Stdlib_Option.flatMap(obj[k], Stdlib_JSON.Decode.string));
    if (options.length !== 2) {
      return;
    }
    let key = options[0];
    if (key === undefined) {
      return;
    }
    let value = options[1];
    if (value !== undefined) {
      return {
        key: key,
        value: value
      };
    }
  });
}

function parsePatches(jsonString) {
  let exit = 0;
  let arr;
  try {
    arr = JSON.parse(jsonString);
    exit = 1;
  } catch (exn) {
    return;
  }
  if (exit === 1) {
    let exit$1 = 0;
    if (Array.isArray(arr)) {
      return Stdlib_Array.filterMap(arr, parsePatch);
    }
    exit$1 = 2;
    if (exit$1 === 2) {
      return Stdlib_Option.map(parsePatch(arr), p => [p]);
    }
  }
}

function applyPatches(values, patches) {
  patches.forEach(patch => {
    values[patch.key] = patch.value;
  });
}

let Values = {
  parsePatch: parsePatch,
  parsePatches: parsePatches,
  applyPatches: applyPatches
};

function subscribe(onPatch, onError) {
  let source = new EventSource(feedSourceUrl);
  source.addEventListener("change", evt => {
    let patches = parsePatches(evt.data);
    if (patches !== undefined) {
      return onPatch(patches);
    } else {
      return onError(Common.Err.make("Failed to parse patch", undefined));
    }
  });
  source.addEventListener("init", evt => {
    let patches = parsePatches(evt.data);
    if (patches !== undefined) {
      return onPatch(patches);
    } else {
      return onError(Common.Err.make("Failed to parse patches", undefined));
    }
  });
  return {
    source: source
  };
}

function unsubscribe(feed) {
  feed.source.close();
}

let Feed = {
  subscribe: subscribe,
  unsubscribe: unsubscribe
};

function setStatus(state, status) {
  let match = typeof status === "object" ? [
      "err",
      Common.Err.string(status.VAL)
    ] : [
      "ok",
      undefined
    ];
  state.status.ack = match[0];
  state.status.err = match[1];
  return state;
}

function patchValues(state, patches) {
  applyPatches(state.values, patches);
  return state;
}

function $$default(fieldsOpt) {
  let fields = fieldsOpt !== undefined ? fieldsOpt : [];
  return {
    fields: fields,
    values: {},
    status: {
      ack: "ok",
      err: undefined
    }
  };
}

async function make() {
  let err = await fetch();
  if (err.TAG === "Ok") {
    return $$default(err._0);
  } else {
    return setStatus($$default(undefined), {
      NAME: "err",
      VAL: err._0
    });
  }
}

let State = {
  setStatus: setStatus,
  patchValues: patchValues,
  $$default: $$default,
  make: make
};

async function make$1() {
  let state = await make();
  return Store.readable(state, (_set, update) => {
    let onPatch = patches => update(__x => patchValues(__x, patches));
    let onError = err => update(__x => setStatus(__x, {
      NAME: "err",
      VAL: err
    }));
    let feedClient = subscribe(onPatch, onError);
    return () => {
      feedClient.source.close();
    };
  });
}

let store = await make$1();

let Store$1;

export {
  getFieldUrl,
  feedSourceUrl,
  Fields,
  Values,
  Feed,
  State,
  Store$1 as Store,
  make$1 as make,
  store,
}
/* store Not a pure module */
