// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Store from "svelte/store";

function subscribeR(store, callback) {
  return store.subscribe(callback);
}

function subscribeW(store, callback) {
  return store.subscribe(callback);
}

function setW(store, value) {
  store.set(value);
}

function updateW(store, fn) {
  store.update(fn);
}

function make(prim) {
  return Store.writable(prim);
}

function get(prim) {
  return Store.get(prim);
}

function readonly(prim) {
  return Store.get(prim);
}

let Writable = {
  make: make,
  get: get,
  set: setW,
  update: updateW,
  subscribe: subscribeW,
  readonly: readonly
};

function get$1(prim) {
  return Store.get(prim);
}

let Readable = {
  get: get$1,
  subscribe: subscribeR
};

function fromR(prim0, prim1) {
  return Store.derived(prim0, prim1);
}

function fromRR(prim0, prim1) {
  return Store.derived(prim0, prim1);
}

function fromW(prim0, prim1) {
  return Store.derived(prim0, prim1);
}

function fromWW(prim0, prim1) {
  return Store.derived(prim0, prim1);
}

function fromRW(prim0, prim1) {
  return Store.derived(prim0, prim1);
}

let Derived = {
  fromR: fromR,
  fromRR: fromRR,
  fromW: fromW,
  fromWW: fromWW,
  fromRW: fromRW
};

export {
  subscribeR,
  subscribeW,
  setW,
  updateW,
  Writable,
  Readable,
  Derived,
}
/* svelte/store Not a pure module */
