// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SvelteStore from "./SvelteStore.res.mjs";

let testStore = SvelteStore.Writable.make(0);

let testStoreD = SvelteStore.Derived.fromW(testStore, i => (i << 1));

function reset() {
  testStore.set(0);
}

function log() {
  let current = SvelteStore.Writable.get(testStore);
  console.log("testStore.value", current);
}

export {
  testStore,
  testStoreD,
  reset,
  log,
}
/* testStore Not a pure module */
