// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as ServerStateStore from "./ServerStateStore.res.mjs";

let store = ServerStateStore.make("//localhost:4000/store/feed", Stdlib_JSON.Decode.string);

export {
  store,
}
/* store Not a pure module */
